/**
 * Русскоязычные шаблоны для сидера: специализации, услуги, диагнозы (МКБ-10), тексты.
 * У каждой специализации — key; у услуги — specKeys (ключи профилей, куда услуга логично входит).
 */

/** @param {import('@faker-js/faker').Faker} faker */
export function createShuffledPool(faker, pool) {
  return faker.helpers.shuffle([...pool]);
}

export function pickAt(shuffledPool, i) {
  return shuffledPool[i % shuffledPool.length];
}

/** Частые лабораторные и вспомогательные профили для пересечения */
const LAB_WIDE = [
  "therapy",
  "cardiology",
  "family_medicine",
  "pediatrics",
  "gastroenterology",
  "nephrology",
  "pulmonology",
  "urology",
  "gynecology",
  "endocrinology",
  "rheumatology",
  "oncology",
  "surgery",
  "traumatology",
  "hematology",
  "infectious",
  "obstetrics",
  "neurology",
  "psychiatry",
];

export const SPECIALIZATION_TEMPLATES = [
  { key: "therapy", name: "Терапия", description: "Диагностика и лечение внутренних болезней взрослых" },
  { key: "cardiology", name: "Кардиология", description: "Заболевания сердечно-сосудистой системы" },
  { key: "pediatrics", name: "Педиатрия", description: "Медицинская помощь детям и подросткам" },
  { key: "dentistry", name: "Стоматология", description: "Заболевания зубов, дёсен и полости рта" },
  { key: "surgery", name: "Хирургия", description: "Оперативное и малоинвазивное лечение" },
  { key: "neurology", name: "Неврология", description: "Заболевания нервной системы" },
  { key: "dermatology", name: "Дерматология", description: "Кожные и венерические заболевания" },
  { key: "ent", name: "Оториноларингология", description: "Болезни уха, горла и носа" },
  { key: "ophthalmology", name: "Офтальмология", description: "Заболевания глаз и зрения" },
  { key: "endocrinology", name: "Эндокринология", description: "Нарушения обмена веществ и гормональной системы" },
  { key: "gastroenterology", name: "Гастроэнтерология", description: "Болезни пищеварительного тракта" },
  { key: "pulmonology", name: "Пульмонология", description: "Заболевания органов дыхания" },
  { key: "rheumatology", name: "Ревматология", description: "Системные заболевания соединительной ткани и суставов" },
  { key: "nephrology", name: "Нефрология", description: "Болезни почек и мочевыводящих путей" },
  { key: "urology", name: "Урология", description: "Заболевания мочеполовой системы у мужчин" },
  { key: "gynecology", name: "Гинекология", description: "Здоровье женской репродуктивной системы" },
  { key: "obstetrics", name: "Акушерство", description: "Ведение беременности и родов" },
  { key: "psychiatry", name: "Психиатрия", description: "Психические расстройства и их лечение" },
  { key: "psychotherapy", name: "Психотерапия", description: "Психологическая коррекция и консультирование" },
  { key: "allergology", name: "Аллергология и иммунология", description: "Аллергические реакции и иммунные нарушения" },
  { key: "infectious", name: "Инфекционные болезни", description: "Диагностика и лечение инфекций" },
  { key: "oncology", name: "Онкология", description: "Диагностика и сопровождение при опухолях" },
  { key: "traumatology", name: "Травматология и ортопедия", description: "Повреждения костей, суставов и мягких тканей" },
  { key: "physiotherapy", name: "Физиотерапия", description: "Восстановительное лечение физическими методами" },
  { key: "ultrasound_dx", name: "Ультразвуковая диагностика", description: "УЗИ-исследования органов и сосудов" },
  { key: "functional_dx", name: "Функциональная диагностика", description: "ЭКГ, Холтер, ЭхоКГ и др." },
  { key: "family_medicine", name: "Семейная медицина", description: "Первичная медико-санитарная помощь семье" },
  { key: "proctology", name: "Проктология", description: "Заболевания прямой кишки и заднего прохода" },
  { key: "mammology", name: "Маммология", description: "Диагностика и лечение заболеваний молочных желёз" },
  { key: "anesthesiology", name: "Анестезиология и реаниматология", description: "Обезболивание и интенсивная терапия" },
  { key: "vascular_surgery", name: "Сосудистая хирургия", description: "Заболевания артерий и вен" },
  { key: "plastic_surgery", name: "Пластическая хирургия", description: "Реконструктивные и эстетические операции" },
  { key: "hematology", name: "Гематология", description: "Заболевания крови и системы кроветворения" },
  { key: "dietology", name: "Диетология", description: "Коррекция питания и массы тела" },
  { key: "narcology", name: "Наркология", description: "Лечение зависимостей" },
  { key: "sports_medicine", name: "Спортивная медицина", description: "Медицинское сопровождение спортсменов" },
  { key: "neonatology", name: "Неонатология", description: "Уход за новорождёнными" },
  { key: "phthisiology", name: "Фтизиатрия", description: "Туберкулёз и заболевания лёгких" },
  { key: "medical_genetics", name: "Медицинская генетика", description: "Наследственные заболевания" },
  { key: "surdology", name: "Сурдология", description: "Нарушения слуха и равновесия" },
];

/** Имя специализации по key (для связки в БД по полю name) */
export function specializationNameForKey(key) {
  const t = SPECIALIZATION_TEMPLATES.find((x) => x.key === key);
  return t?.name ?? null;
}

export const DEMO_PSYCHIATRY_SPEC_KEY = "psychiatry";

export const SERVICE_TEMPLATES = [
  {
    name: "Первичная консультация терапевта",
    description: "Осмотр, сбор анамнеза, назначения",
    duration_minutes: 30,
    priceMin: 1500,
    priceMax: 3500,
    specKeys: ["therapy", "family_medicine"],
  },
  {
    name: "Повторный приём терапевта",
    description: "Контроль лечения, коррекция терапии",
    duration_minutes: 20,
    priceMin: 1200,
    priceMax: 2500,
    specKeys: ["therapy", "family_medicine"],
  },
  {
    name: "Консультация кардиолога",
    description: "Оценка сердечно-сосудистого риска",
    duration_minutes: 40,
    priceMin: 2200,
    priceMax: 4500,
    specKeys: ["cardiology"],
  },
  {
    name: "ЭКГ в покое",
    description: "Снятие и интерпретация электрокардиограммы",
    duration_minutes: 20,
    priceMin: 800,
    priceMax: 1800,
    specKeys: ["cardiology", "functional_dx", "therapy", "family_medicine"],
  },
  {
    name: "ЭхоКГ",
    description: "Ультразвуковое исследование сердца",
    duration_minutes: 45,
    priceMin: 2500,
    priceMax: 5500,
    specKeys: ["cardiology", "functional_dx"],
  },
  {
    name: "Суточное мониторирование АД",
    description: "СМАД с выдачей заключения",
    duration_minutes: 30,
    priceMin: 1800,
    priceMax: 3200,
    specKeys: ["cardiology", "functional_dx", "nephrology", "therapy"],
  },
  {
    name: "Консультация педиатра",
    description: "Приём ребёнка, рекомендации родителям",
    duration_minutes: 30,
    priceMin: 1600,
    priceMax: 3200,
    specKeys: ["pediatrics"],
  },
  {
    name: "Профилактический осмотр ребёнка",
    description: "Осмотр по возрасту, прививочный статус",
    duration_minutes: 25,
    priceMin: 1400,
    priceMax: 2800,
    specKeys: ["pediatrics"],
  },
  {
    name: "Приём стоматолога-терапевта",
    description: "Осмотр полости рта, план лечения",
    duration_minutes: 30,
    priceMin: 1200,
    priceMax: 2500,
    specKeys: ["dentistry"],
  },
  {
    name: "Профессиональная гигиена полости рта",
    description: "Удаление зубного камня и налёта, полировка",
    duration_minutes: 60,
    priceMin: 3500,
    priceMax: 7500,
    specKeys: ["dentistry"],
  },
  {
    name: "Лечение кариеса одного зуба",
    description: "Пломбирование с анестезией",
    duration_minutes: 45,
    priceMin: 2500,
    priceMax: 6000,
    specKeys: ["dentistry"],
  },
  {
    name: "Консультация невролога",
    description: "Неврологический статус, рекомендации",
    duration_minutes: 40,
    priceMin: 2000,
    priceMax: 4200,
    specKeys: ["neurology"],
  },
  {
    name: "ЭЭГ",
    description: "Электроэнцефалография",
    duration_minutes: 60,
    priceMin: 2200,
    priceMax: 4800,
    specKeys: ["neurology", "functional_dx"],
  },
  {
    name: "Консультация дерматолога",
    description: "Осмотр кожи, диагностика дерматозов",
    duration_minutes: 30,
    priceMin: 1700,
    priceMax: 3500,
    specKeys: ["dermatology"],
  },
  {
    name: "Удаление доброкачественного новообразования кожи",
    description: "Малоинвазивное удаление с гистологией",
    duration_minutes: 30,
    priceMin: 2000,
    priceMax: 8000,
    specKeys: ["dermatology", "plastic_surgery"],
  },
  {
    name: "Приём ЛОР-врача",
    description: "Осмотр уха, горла, носа",
    duration_minutes: 30,
    priceMin: 1600,
    priceMax: 3200,
    specKeys: ["ent"],
  },
  {
    name: "Промывание носа методом кукушка",
    description: "Процедура с антисептиком",
    duration_minutes: 20,
    priceMin: 800,
    priceMax: 1500,
    specKeys: ["ent"],
  },
  {
    name: "Консультация офтальмолога",
    description: "Проверка остроты зрения, осмотр глазного дна",
    duration_minutes: 35,
    priceMin: 1800,
    priceMax: 3800,
    specKeys: ["ophthalmology"],
  },
  {
    name: "Подбор контактных линз",
    description: "Подбор и обучение",
    duration_minutes: 45,
    priceMin: 1500,
    priceMax: 3000,
    specKeys: ["ophthalmology"],
  },
  {
    name: "Консультация эндокринолога",
    description: "Оценка углеводного и липидного обмена",
    duration_minutes: 40,
    priceMin: 2200,
    priceMax: 4500,
    specKeys: ["endocrinology"],
  },
  {
    name: "УЗИ щитовидной железы",
    description: "Ультразвуковое исследование",
    duration_minutes: 25,
    priceMin: 1200,
    priceMax: 2200,
    specKeys: ["endocrinology", "ultrasound_dx"],
  },
  {
    name: "Консультация гастроэнтеролога",
    description: "ЖКТ, назначение обследований",
    duration_minutes: 40,
    priceMin: 2100,
    priceMax: 4200,
    specKeys: ["gastroenterology"],
  },
  {
    name: "УЗИ брюшной полости",
    description: "Печень, желчный пузырь, поджелудочная",
    duration_minutes: 30,
    priceMin: 1400,
    priceMax: 2800,
    specKeys: ["gastroenterology", "ultrasound_dx", "nephrology"],
  },
  {
    name: "Консультация пульмонолога",
    description: "Дыхательная система, спирометрия по показаниям",
    duration_minutes: 35,
    priceMin: 1900,
    priceMax: 3800,
    specKeys: ["pulmonology"],
  },
  {
    name: "Спирометрия",
    description: "Исследование функции внешнего дыхания",
    duration_minutes: 30,
    priceMin: 900,
    priceMax: 1800,
    specKeys: ["pulmonology", "functional_dx"],
  },
  {
    name: "Консультация ревматолога",
    description: "Суставы, соединительная ткань",
    duration_minutes: 40,
    priceMin: 2300,
    priceMax: 4800,
    specKeys: ["rheumatology"],
  },
  {
    name: "Консультация нефролога",
    description: "Функция почек, артериальное давление",
    duration_minutes: 40,
    priceMin: 2200,
    priceMax: 4500,
    specKeys: ["nephrology"],
  },
  {
    name: "Консультация уролога",
    description: "Мочеполовая система",
    duration_minutes: 30,
    priceMin: 1800,
    priceMax: 3800,
    specKeys: ["urology"],
  },
  {
    name: "УЗИ почек и мочевого пузыря",
    description: "Ультразвуковое исследование",
    duration_minutes: 25,
    priceMin: 1300,
    priceMax: 2400,
    specKeys: ["urology", "nephrology", "ultrasound_dx"],
  },
  {
    name: "Консультация гинеколога",
    description: "Гинекологический осмотр",
    duration_minutes: 30,
    priceMin: 1800,
    priceMax: 4000,
    specKeys: ["gynecology"],
  },
  {
    name: "Кольпоскопия",
    description: "Исследование шейки матки",
    duration_minutes: 25,
    priceMin: 1500,
    priceMax: 3200,
    specKeys: ["gynecology"],
  },
  {
    name: "Ведение беременности (один визит)",
    description: "Осмотр, УЗИ по показаниям",
    duration_minutes: 40,
    priceMin: 2000,
    priceMax: 4500,
    specKeys: ["obstetrics", "gynecology"],
  },
  {
    name: "Консультация психотерапевта",
    description: "Психологическая беседа 50 минут",
    duration_minutes: 50,
    priceMin: 2500,
    priceMax: 6000,
    specKeys: ["psychotherapy", "psychiatry"],
  },
  {
    name: "Консультация аллерголога",
    description: "Аллергологический статус, план обследования",
    duration_minutes: 40,
    priceMin: 2000,
    priceMax: 4200,
    specKeys: ["allergology"],
  },
  {
    name: "Кожные пробы на аллергены",
    description: "Скарификационное тестирование",
    duration_minutes: 45,
    priceMin: 2800,
    priceMax: 5500,
    specKeys: ["allergology"],
  },
  {
    name: "Консультация инфекциониста",
    description: "Инфекции, вакцинация",
    duration_minutes: 35,
    priceMin: 1900,
    priceMax: 3800,
    specKeys: ["infectious"],
  },
  {
    name: "Консультация онколога",
    description: "Оценка риска, направление на обследование",
    duration_minutes: 45,
    priceMin: 2500,
    priceMax: 5500,
    specKeys: ["oncology"],
  },
  {
    name: "Консультация травматолога-ортопеда",
    description: "Осмотр опорно-двигательного аппарата",
    duration_minutes: 30,
    priceMin: 1700,
    priceMax: 3500,
    specKeys: ["traumatology"],
  },
  {
    name: "Пункция сустава",
    description: "Манипуляция под местной анестезией",
    duration_minutes: 30,
    priceMin: 2000,
    priceMax: 4500,
    specKeys: ["traumatology", "rheumatology"],
  },
  {
    name: "Массаж лечебный (сеанс)",
    description: "30 минут по назначению врача",
    duration_minutes: 30,
    priceMin: 1200,
    priceMax: 2500,
    specKeys: ["physiotherapy", "traumatology", "neurology"],
  },
  {
    name: "Физиотерапия (сеанс)",
    description: "Электрофорез или УВЧ по назначению",
    duration_minutes: 20,
    priceMin: 500,
    priceMax: 1200,
    specKeys: ["physiotherapy"],
  },
  {
    name: "УЗИ малого таза",
    description: "Трансабдоминально или трансвагинально",
    duration_minutes: 25,
    priceMin: 1400,
    priceMax: 2600,
    specKeys: ["gynecology", "urology", "ultrasound_dx"],
  },
  {
    name: "УЗИ сосудов шеи (дуплексное сканирование)",
    description: "Брахиоцефальные артерии",
    duration_minutes: 35,
    priceMin: 2200,
    priceMax: 4200,
    specKeys: ["cardiology", "neurology", "vascular_surgery", "ultrasound_dx"],
  },
  {
    name: "Общий анализ крови",
    description: "Забор крови, результат в день обращения",
    duration_minutes: 15,
    priceMin: 400,
    priceMax: 900,
    specKeys: LAB_WIDE,
  },
  {
    name: "Биохимический анализ крови (расширенный)",
    description: "Печёночные пробы, липиды, глюкоза",
    duration_minutes: 15,
    priceMin: 1200,
    priceMax: 2800,
    specKeys: LAB_WIDE,
  },
  {
    name: "Общий анализ мочи",
    description: "Лабораторное исследование",
    duration_minutes: 15,
    priceMin: 350,
    priceMax: 700,
    specKeys: LAB_WIDE.filter((k) => k !== "dentistry"),
  },
  {
    name: "Коагулограмма",
    description: "Свёртываемость крови",
    duration_minutes: 15,
    priceMin: 600,
    priceMax: 1400,
    specKeys: [
      "therapy",
      "cardiology",
      "surgery",
      "anesthesiology",
      "gynecology",
      "obstetrics",
      "hematology",
      "oncology",
    ],
  },
  {
    name: "Рентгенография грудной клетки",
    description: "Одна проекция",
    duration_minutes: 20,
    priceMin: 900,
    priceMax: 1800,
    specKeys: ["pulmonology", "cardiology", "therapy", "surgery", "traumatology", "oncology", "infectious"],
  },
  {
    name: "КТ органов грудной клетки",
    description: "С контрастированием по показаниям",
    duration_minutes: 45,
    priceMin: 4500,
    priceMax: 12000,
    specKeys: ["pulmonology", "oncology", "cardiology", "surgery"],
  },
  {
    name: "Первичная консультация психиатра",
    description: "Осмотр, сбор анамнеза, план ведения",
    duration_minutes: 45,
    priceMin: 2200,
    priceMax: 5000,
    specKeys: ["psychiatry"],
  },
  {
    name: "Повторный приём психиатра",
    description: "Контроль терапии, коррекция схемы лечения",
    duration_minutes: 30,
    priceMin: 1800,
    priceMax: 4000,
    specKeys: ["psychiatry"],
  },
  {
    name: "Подбор и коррекция антидепрессантной терапии",
    description: "Психофармакотерапия по показаниям, мониторинг переносимости",
    duration_minutes: 40,
    priceMin: 2500,
    priceMax: 5500,
    specKeys: ["psychiatry"],
  },
  {
    name: "Кризисная психиатрическая консультация",
    description: "Оценка острого состояния, рекомендации по тактике",
    duration_minutes: 60,
    priceMin: 3000,
    priceMax: 7000,
    specKeys: ["psychiatry"],
  },
  {
    name: "Консультация хирурга",
    description: "Предоперационная оценка, показания к операции",
    duration_minutes: 35,
    priceMin: 2000,
    priceMax: 4200,
    specKeys: ["surgery", "vascular_surgery", "plastic_surgery"],
  },
  {
    name: "Перевязка послеоперационной раны",
    description: "Обработка и перевязка в амбулаторных условиях",
    duration_minutes: 20,
    priceMin: 800,
    priceMax: 1800,
    specKeys: ["surgery"],
  },
  {
    name: "Консультация анестезиолога",
    description: "Оценка рисков анестезии, подготовка к вмешательству",
    duration_minutes: 30,
    priceMin: 2000,
    priceMax: 4000,
    specKeys: ["anesthesiology", "surgery"],
  },
  {
    name: "Консультация сосудистого хирурга",
    description: "Обследование вен и артерий, план лечения",
    duration_minutes: 40,
    priceMin: 2300,
    priceMax: 4800,
    specKeys: ["vascular_surgery"],
  },
  {
    name: "УЗИ вен нижних конечностей",
    description: "Оценка венозного оттока, варикозная болезнь",
    duration_minutes: 40,
    priceMin: 2000,
    priceMax: 3800,
    specKeys: ["vascular_surgery", "ultrasound_dx"],
  },
  {
    name: "Консультация пластического хирурга",
    description: "Осмотр, обсуждение объёма и рисков вмешательства",
    duration_minutes: 45,
    priceMin: 3500,
    priceMax: 8000,
    specKeys: ["plastic_surgery"],
  },
  {
    name: "Консультация проктолога",
    description: "Осмотр, ректальное исследование по показаниям",
    duration_minutes: 30,
    priceMin: 1900,
    priceMax: 3800,
    specKeys: ["proctology"],
  },
  {
    name: "Ректороманоскопия",
    description: "Эндоскопическое исследование прямой кишки",
    duration_minutes: 25,
    priceMin: 2200,
    priceMax: 4500,
    specKeys: ["proctology", "gastroenterology"],
  },
  {
    name: "Консультация маммолога",
    description: "Осмотр молочных желёз, интерпретация обследований",
    duration_minutes: 35,
    priceMin: 2100,
    priceMax: 4200,
    specKeys: ["mammology", "oncology"],
  },
  {
    name: "УЗИ молочных желёз",
    description: "Ультразвуковое исследование",
    duration_minutes: 30,
    priceMin: 1600,
    priceMax: 3000,
    specKeys: ["mammology", "ultrasound_dx", "gynecology"],
  },
  {
    name: "Суточное мониторирование ЭКГ (Холтер)",
    description: "Запись ритма сердца в течение суток",
    duration_minutes: 30,
    priceMin: 2500,
    priceMax: 4800,
    specKeys: ["functional_dx", "cardiology"],
  },
  {
    name: "Консультация гематолога",
    description: "Анализ показателей крови, план дообследования",
    duration_minutes: 40,
    priceMin: 2300,
    priceMax: 4800,
    specKeys: ["hematology", "oncology"],
  },
];

/** Коды и названия по МКБ-10; category — глава (римскими цифрами) */
export const DIAGNOSIS_TEMPLATES = [
  { code: "I10", name: "Эссенциальная (первичная) гипертензия", category: "IX" },
  { code: "E11.9", name: "Сахарный диабет 2 типа без осложнений", category: "IV" },
  { code: "J06.9", name: "Острая инфекция верхних дыхательных путей неуточнённая", category: "X" },
  { code: "K29.8", name: "Дуоденит неуточнённый", category: "XI" },
  { code: "K02.1", name: "Кариес дентина", category: "XI" },
  { code: "M54.5", name: "Боль в пояснице", category: "XIII" },
  { code: "G43.1", name: "Мигрень с аурой", category: "VI" },
  { code: "H52.1", name: "Миопия", category: "VII" },
  { code: "J45.0", name: "Бронхиальная астма преимущественно аллергическая", category: "X" },
  { code: "N39.0", name: "Инфекция мочевыводящих путей без установленной локализации", category: "XIV" },
  { code: "L20.9", name: "Атопический дерматит неуточнённый", category: "XII" },
  { code: "F41.1", name: "Генерализованное тревожное расстройство", category: "V" },
  { code: "B34.9", name: "Вирусная инфекция неуточнённая", category: "I" },
  { code: "A09", name: "Диарея и гастроэнтерит предположительно инфекционного происхождения", category: "I" },
  { code: "R50.9", name: "Лихорадка неуточнённая", category: "XVIII" },
  { code: "R51", name: "Головная боль", category: "XVIII" },
  { code: "R10.4", name: "Другие и неуточнённые боли в животе", category: "XVIII" },
  { code: "D50.9", name: "Железодефицитная анемия неуточнённая", category: "III" },
  { code: "E03.9", name: "Гипотиреоз неуточнённый", category: "IV" },
  { code: "E78.5", name: "Гиперлипидемия неуточнённая", category: "IV" },
  { code: "I20.9", name: "Стенокардия неуточнённая", category: "IX" },
  { code: "I25.1", name: "Атеросклеротическая болезнь сердца", category: "IX" },
  { code: "J18.9", name: "Пневмония неуточнённого возбудителя", category: "X" },
  { code: "K21.9", name: "Гастроэзофагеальная рефлюксная болезнь без эзофагита", category: "XI" },
  { code: "K59.0", name: "Запор", category: "XI" },
  { code: "M79.1", name: "Миалгия", category: "XIII" },
  { code: "H66.9", name: "Острый средний отит неуточнённый", category: "VIII" },
  { code: "J02.9", name: "Острый фарингит неуточнённый", category: "X" },
  { code: "B02.9", name: "Опоясывающий лишай без осложнений", category: "I" },
  { code: "C50.9", name: "Злокачественное новообразование молочной железы неуточнённой части", category: "II" },
  { code: "Z00.0", name: "Общий медицинский осмотр", category: "XXI" },
  { code: "Z01.8", name: "Другие уточнённые специальные обследования", category: "XXI" },
  { code: "F32.1", name: "Умеренный депрессивный эпизод", category: "V" },
  { code: "G47.0", name: "Нарушения засыпания и поддержания сна [бессонница]", category: "VI" },
  { code: "L70.0", name: "Угри обыкновенные", category: "XII" },
  { code: "N20.0", name: "Камень почки", category: "XIV" },
  { code: "O24.4", name: "Сахарный диабет, возникший в период беременности", category: "XV" },
  { code: "S93.4", name: "Растяжение и повреждение связок голеностопного сустава", category: "XIX" },
  { code: "T14.03", name: "Поверхностное повреждение неуточнённой области тела", category: "XIX" },
  { code: "U07.1", name: "COVID-19, вирус идентифицирован", category: "XXII" },
  { code: "K25.9", name: "Язва желудка без кровотечения или перфорации", category: "XI" },
  { code: "K29.7", name: "Гастрит неуточнённый", category: "XI" },
  { code: "J44.1", name: "Обострение ХОБЛ с инфекцией нижних дыхательных путей", category: "X" },
  { code: "E66.9", name: "Ожирение неуточнённое", category: "IV" },
  { code: "I48.0", name: "Пароксизмальная форма фибрилляции предсердий", category: "IX" },
  { code: "M17.9", name: "Гонартроз неуточнённый", category: "XIII" },
  { code: "H10.9", name: "Конъюнктивит неуточнённый", category: "VII" },
  { code: "R06.0", name: "Одышка", category: "XVIII" },
  { code: "R07.4", name: "Боль в груди неуточнённая", category: "XVIII" },
];

export const RU_TEXT = {
  bio: [
    "Врач высшей категории, регулярно повышает квалификацию.",
    "Специализируется на ведении пациентов с хроническими заболеваниями.",
    "Член профессиональных медицинских ассоциаций.",
    "Ведёт приём взрослых пациентов, опыт работы в стационаре.",
    "Проводит диагностику и подбор индивидуальной терапии.",
    "Уделяет внимание профилактике и здоровому образу жизни.",
    "Практикует доказательный подход к назначениям.",
    "Консультирует по вопросам подготовки к операции и реабилитации.",
  ],
  reviews: [
    "Внимательный врач, всё объяснил доступно. Рекомендую.",
    "Приём прошёл вовремя, без лишней суеты. Осталась довольна.",
    "Профессионально и доброжелательно. Помогли с диагнозом.",
    "Хорошая клиника, врач компетентный, назначения по делу.",
    "Спасибо за терпение и подробные ответы на вопросы.",
    "Чёткий план обследования, всё понятно с первого визита.",
    "Комфортно на приёме, чувствуется опыт специалиста.",
    "Вернусь на повторный приём — доверяю этому доктору.",
  ],
  cancelReasons: [
    "Пациент отменил по личным обстоятельствам.",
    "Перенос по болезни пациента.",
    "Не удалось связаться с пациентом для подтверждения.",
    "Пациент записался к другому специалисту.",
    "Отмена по просьбе пациента, форс-мажор.",
    "Дублирующая запись, оставлена одна консультация.",
  ],
};

export const ROOM_PURPOSES = [
  "терапия",
  "кардиология",
  "педиатрия",
  "стоматология",
  "ЛОР",
  "неврология",
  "процедурный",
  "УЗИ",
  "функциональная диагностика",
  "хирургия",
  "гинекология",
  "офтальмология",
];
